<a href="https://colab.research.google.com/github/chanyut12/probability-and-statistics/blob/main/66160295_w1_G2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ให้นิสิต เลือกเมนู File-->Save a copy in drive เพื่อคัดลอกไฟล์ไปไว้ในไดร์ฟของนิสิตก่อน และเปลี่ยนชื่อไฟล์เป็น รหัสนิสิต_w1 ค่ะ**

จงเขียนโปรแกรม เพื่อหาค่าที่โจทย์ต้องการและแสดงผลลัพธ์ออกทางหน้าจอ

1. จงสร้างอาร์เรย์ 1 มิติ ที่มีสมาชิกเป็นเลขสุ่มที่เป็นจำนวนเต็มที่มีค่า 1 ถึง 20 จำนวน 24 ตัว

2. จงเรียงลำดับข้อมูลของอาร์เรย์ที่ได้จากข้อ 1. โดยเรียงจากค่าน้อยไปค่ามาก และเรียงจากค่ามากไปค่าน้อย

3. จงหาค่ามากที่สุด ค่าน้อยที่สุด ของอาร์เรย์ในข้อ 1.

4. จงหาค่าเฉลี่ย ค่ามัธยฐาน ค่าฐานนิยม ของอาร์เรย์ในข้อ 1.

5. จงเปลี่ยนมิติของอาร์เรย์ที่ได้จากข้อ 1. เป็นอาร์เรย์ 2 มิติขนาด 6 แถว 4 คอลัมน์

6. จงเรียงลำดับข้อมูลของอาร์เรย์ที่ได้จากข้อ 5. ตามแนวแถว และแนวคอลัมน์ โดยเรียงจากค่าน้อยไปค่ามาก

7. จงหาค่าเฉลี่ย ค่ามัธยฐาน ค่าฐานนิยม ในแต่ละแถว และในแต่ละคอลัมน์ของอาร์เรย์ในข้อ 5.

8. จงเปลี่ยนมิติของอาร์เรย์ที่ได้จากข้อ 5. กลับเป็นอาร์เรย์ 1 มิติที่มีสมาชิก 24 ตัว ซึ่งจะได้ผลลัพธ์เหมือนกับข้อ 1.

9. จงสร้างข้อมูลแบบสุ่มของอาชีพ (doctor, barber, trader, programmer) คนที่มาอบรมโครงการเรียนรู้เพื่อสุขภาวะจิต จำนวน 50 คน

10. จงสร้างตารางแจกแจงความถี่ของอาร์เรย์ในข้อ 9. แสดงจำนวนคนที่มาอบรมโครงการ แยกตามแต่ละอาชีพ





In [ ]:
#ชื่อ................รหัส.........


In [ ]:
!pip install numpy

In [ ]:
#1
import random

x = [random.randint(1,21) for i in range(24)]
y = np.random.randint(1,21,24)
print(x)
print(y)

[6, 9, 19, 3, 21, 3, 19, 12, 5, 14, 10, 5, 9, 3, 1, 4, 2, 10, 10, 3, 13, 17, 4, 15]
[14  7 15 14 16  6 10 19 15 18 10 12 12 18  7  4 18  1 19  8 11  2  3 16]


In [ ]:
#2
import numpy as np
print(np.sort(x))
print(np.sort(x))

[ 1  2  3  3  3  3  4  4  5  5  6  9  9 10 10 10 12 13 14 15 17 19 19 21]
[ 1  2  3  3  3  3  4  4  5  5  6  9  9 10 10 10 12 13 14 15 17 19 19 21]


In [ ]:
#3
print(np.max(x))
print(np.min(x))

21
1


In [ ]:
#4
from scipy import stats
print("mean : " , np.mean(x))
print("median : " , np.median(x))
print('mode g (column)=',stats.mode(x))


mean :  9.041666666666666
median :  9.0
mode g (column)= ModeResult(mode=3, count=4)


In [ ]:
#5
import numpy as np
x = np.array(x)
z = x.reshape(6,4)
print(z)

[[ 6  9 19  3]
 [21  3 19 12]
 [ 5 14 10  5]
 [ 9  3  1  4]
 [ 2 10 10  3]
 [13 17  4 15]]


In [ ]:
#6
print('sorted x (row)=',np.sort(z)) #axis = 1 เรียงตามแถว
print('sorted x (column)=',np.sort(z,axis = 0))


sorted x (row)= [[ 3  6  9 19]
 [ 3 12 19 21]
 [ 5  5 10 14]
 [ 1  3  4  9]
 [ 2  3 10 10]
 [ 4 13 15 17]]
sorted x (column)= [[ 2  3  1  3]
 [ 5  3  4  3]
 [ 6  9 10  4]
 [ 9 10 10  5]
 [13 14 19 12]
 [21 17 19 15]]


In [ ]:
# #7
# from scipy import stats

# print('mean0 z =',np.mean(z[0] , axis = 0))
# print('mean1 z =',np.mean(z[1] , axis = 0))
# print('mean2 z =',np.mean(z[2] , axis = 0))
# print('mean3 z =',np.mean(z[3] , axis = 0))
# print('mean4 z =',np.mean(z[4] , axis = 0))
# print('mean5 z =',np.mean(z[5] , axis = 0))

# print()

# print('median0 z =',np.median(z[0] , axis = 0))
# print('median1 z =',np.median(z[1] , axis = 0))
# print('median2 z =',np.median(z[2] , axis = 0))
# print('median3 z =',np.median(z[3] , axis = 0))
# print('median4 z =',np.median(z[4] , axis = 0))
# print('median5 z =',np.median(z[5] , axis = 0))

# print()
# print('mean0 z =',np.mean(z[][0] , axis = 0))
# print('mean1 z =',np.mean(z[][1] , axis = 0))
# print('mean2 z =',np.mean(z[][2] , axis = 0))
# print('mean3 z =',np.mean(z[][3] , axis = 0))
# print('mean4 z =',np.mean(z[][4] , axis = 0))
# print('mean5 z =',np.mean(z[][5] , axis = 0))

# print('mode z (row)=',stats.mode(z , axis = 1))
# print('mode z (column)=',stats.mode(z , axis = 0))



# print('mean x =',np.median(z , axis = 1))
# print('median x =',np.median(x,  axis = 0))
# print('mode x (column)=',stats.mode(x))


In [ ]:
#7
import numpy as np
from statistics import median, mode

#  each row
row_means = np.mean(z, axis=1)
row_medians = np.median(z, axis=1)
row_modes = [int(mode(row)) for row in z]

#  each column
column_means = np.mean(z, axis=0)
column_medians = np.median(z, axis=0)
column_modes = [int(mode(z[:, i])) for i in range(z.shape[1])]

# Print the results
print("Row Means:", row_means)
print("Row Medians:", row_medians)
print("Row Modes:", row_modes)
print("Column Means:", column_means)
print("Column Medians:", column_medians)
print("Column Modes:", column_modes)



Row Means: [ 9.25 13.75  8.5   4.25  6.25 12.25]
Row Medians: [ 7.5 15.5  7.5  3.5  6.5 14. ]
Row Modes: [6, 21, 5, 9, 10, 13]
Column Means: [ 9.33333333  9.33333333 10.5         7.        ]
Column Medians: [ 7.5  9.5 10.   4.5]
Column Modes: [6, 3, 19, 3]


In [ ]:
#8
z1 = z.reshape(24)
print(z1)

[ 6  9 19  3 21  3 19 12  5 14 10  5  9  3  1  4  2 10 10  3 13 17  4 15]


In [ ]:
#9
gr = ['doctor','barber','trader','programmer']
print(gr)
gra = [random.choice(gr) for i in range(50)]
print(gra)
# print("doctor =",grade.count("doctor"))
# print("barber =",grade.count("barber"))
# print("trader =",grade.count("trader"))
# print("programmer =",grade.count("programmer"))

# print("all occuoation =",len(grade))

['doctor', 'barber', 'trader', 'programmer']
['trader', 'trader', 'trader', 'trader', 'barber', 'trader', 'doctor', 'doctor', 'programmer', 'programmer', 'trader', 'trader', 'barber', 'trader', 'barber', 'programmer', 'barber', 'barber', 'barber', 'programmer', 'doctor', 'programmer', 'barber', 'trader', 'barber', 'programmer', 'barber', 'programmer', 'trader', 'trader', 'barber', 'programmer', 'barber', 'barber', 'trader', 'doctor', 'trader', 'barber', 'programmer', 'barber', 'trader', 'trader', 'programmer', 'barber', 'doctor', 'programmer', 'programmer', 'barber', 'doctor', 'trader']


In [ ]:
#10
print("doctor =",gra.count("doctor"))
print("barber =",gra.count("barber"))
print("trader =",gra.count("trader"))
print("programmer =",gra.count("programmer"))
print("all occuoation =",len(gra))
import pandas as pd
a = pd.Series(gra)
print(a)
a.value_counts() #สำหรับค่าแต่ละค่าในชุด

doctor = 6
barber = 16
trader = 16
programmer = 12
all occuoation = 50
0         trader
1         trader
2         trader
3         trader
4         barber
5         trader
6         doctor
7         doctor
8     programmer
9     programmer
10        trader
11        trader
12        barber
13        trader
14        barber
15    programmer
16        barber
17        barber
18        barber
19    programmer
20        doctor
21    programmer
22        barber
23        trader
24        barber
25    programmer
26        barber
27    programmer
28        trader
29        trader
30        barber
31    programmer
32        barber
33        barber
34        trader
35        doctor
36        trader
37        barber
38    programmer
39        barber
40        trader
41        trader
42    programmer
43        barber
44        doctor
45    programmer
46    programmer
47        barber
48        doctor
49        trader
dtype: object


trader        16
barber        16
programmer    12
doctor         6
dtype: int64